-- Guide.user used to be @OneToOne, so Hibernate created a UNIQUE index on guide.user_id and each user
-- could write only one guide. Guides are now @ManyToOne.
-- The foreign key on user_id needs an index, and the unique index may be the only one, so a plain
-- index is added first. Index names were generated by Hibernate, so they are looked up rather than
-- hard-coded. No data is modified. Written to be safely re-runnable (MySQL DDL is not transactional).

SET @plain_index_exists := (SELECT COUNT(*) FROM information_schema.statistics
    WHERE table_schema = DATABASE() AND table_name = 'guide' AND index_name = 'idx_guide_user_id');
SET @ddl := IF(@plain_index_exists = 0, 'CREATE INDEX idx_guide_user_id ON guide (user_id)', 'DO 0');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @unique_index := (SELECT s.index_name FROM information_schema.statistics s
    WHERE s.table_schema = DATABASE() AND s.table_name = 'guide' AND s.column_name = 'user_id'
      AND s.non_unique = 0 AND s.index_name <> 'PRIMARY'
      AND (SELECT COUNT(*) FROM information_schema.statistics s2
           WHERE s2.table_schema = s.table_schema AND s2.table_name = s.table_name
             AND s2.index_name = s.index_name) = 1
    LIMIT 1);
SET @ddl := IF(@unique_index IS NULL, 'DO 0', CONCAT('ALTER TABLE guide DROP INDEX `', @unique_index, '`'));
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
